feat: Adiciona verificacao de saude da api antes de processar conteudos
betrybe/process-content pull request #27
Opened 2021-01-26 15:11 UTC by Caciquez

2021-01-26 15:15 UTC, raigons approved these changes

2021-01-26 15:17 UTC, raigons commented on src/service.js
> +      await sleep(15000);
💅

2021-01-26 15:26 UTC, raigons commented on __tests__/main.test.js
> +  test('throw error when heroku isn`t available yet', async () => {
suddenly a huge wild test appears

2021-01-27 12:18 UTC, caironoleto requested changes
Duas coisas:

- Faltou colocar contexto da descrição. É super importante que os pull requests tenham contexto, para acelerar o processo e qualquer pessoa consiga fazer code review;
- Faltou seguir o [processo de code review](https://playbook.betrybe.com/docs/funcionais/technology/fluxo-de-desenvolvimento/#depois-que-voc%C3%AA-finalizou-seu-c%C3%B3digo);

2021-01-27 12:18 UTC, caironoleto commented on action.yml
> +  herokuHealthApiURL:
Estar no heroku ou outro lugar é irrelevante, então da pra remover do nome do atributo.

```suggestion
  applicationHealthApiURL:
```

2021-01-27 12:25 UTC, Caciquez commented
> Duas coisas:
> 
> * Faltou colocar contexto da descrição. É super importante que os pull requests tenham contexto, para acelerar o processo e qualquer pessoa consiga fazer code review;
Boa, fiquei na dúvida pois por ser um repósitorio aberto, foi pedido que não se colocasse descrição com informações do mesmo no PR 🤔 

> * Faltou seguir o [processo de code review](https://playbook.betrybe.com/docs/funcionais/technology/fluxo-de-desenvolvimento/#depois-que-voc%C3%AA-finalizou-seu-c%C3%B3digo);

Os outros times não tem acesso a esse repo ainda, sendo assim não consigo marcar o tech-code-review vou ver como posso configurar (:

2021-01-27 12:27 UTC, caironoleto commented
@Caciquez da pra trazer contexto sem trazer informação sensível. São coisas diferentes.

Sobre o acesso, eu dei acesso e agora da pra seguir o processo nesse PR também.

2021-01-27 19:14 UTC, gknedo approved these changes

2021-01-27 19:18 UTC, caironoleto approved these changes

2021-01-27 21:13 UTC, merged