[LEARN 968] Nova nomeclatura de criacao de versao
betrybe/process-content pull request #33
Opened 2021-02-01 19:08 UTC by Caciquez

2021-02-01 19:27 UTC, caironoleto requested changes

2021-02-01 19:27 UTC, caironoleto commented on action.yml
> +  prNumber:
deveria ser `pullRequestId`, pra seguir a mesma nomenclatura.

2021-02-01 19:27 UTC, caironoleto commented on src/main.js
> +    pull_request_merged_at: mergedAt,
faz sentido também alterar o `mergedAt` pra seguir a mesma nomenclatura: `pullRequestMergedAt`.

2021-02-01 19:37 UTC, raigons commented on .env.example
> +PULL_REQUEST_ID=666
👿

2021-02-01 19:41 UTC, raigons approved these changes

2021-02-01 20:34 UTC, caironoleto approved these changes

2021-02-02 11:02 UTC, gknedo approved these changes

2021-02-04 17:32 UTC, raigons commented
@Caciquez faz o `npm run package` pra incluir o dist

2021-02-04 17:41 UTC, merged